name: Tâche météo quotidienne

on:
  schedule:
  - cron: '0 23 * * *'  # Tous les jours à 23h UTC (00h Bénin)  workflow_dispatch:

jobs:
  fetch-and-store-weather:
    runs-on: ubuntu-latest

    steps:
    - name: Récupérer le dépôt
      uses: actions/checkout@v3

    - name: Configurer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install requests firebase-admin pytz

    - name: Exécuter le script
      env:
        FIREBASE_KEY_JSON: ${{ secrets.FIREBASE_KEY_JSON }}
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        VILLE_METEO: ${{ secrets.VILLE_METEO }}
      run: python script.py
